name: CI Pipeline

on:
  workflow_dispatch:
    # Add additional trigger events as needed (e.g., push, pull_request, etc.)

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MYSQL_ROOT_PASSWORD: root

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.actor == 'pablo-code-org'
    steps:
      - name: Cache Checked-Out Repository
        uses: actions/cache@v2
        with:
          path: |
            code-dot-org
          key: checkout-${{ runner.os }}-${{ hashFiles('**') }}
          restore-keys: checkout-${{ runner.os }}-

      - name: Checkout Repository
        if: steps.cache-checked-out-repository.outputs.cache-hit != 'true'
        run: git clone https://github.com/code-dot-org/code-dot-org.git ./code-dot-org
